"""empty message

Revision ID: 30d017ee0964
Revises: 04c6225a43f5
Create Date: 2019-09-03 15:54:03.563366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d017ee0964'
down_revision = '04c6225a43f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='post_prompt', column_name='content', new_column_name='text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(table_name='post_prompt', column_name='text', new_column_name='content')
    # ### end Alembic commands ###
