"""empty message

Revision ID: 56b21e4e1038
Revises: e009a4fff809
Create Date: 2019-09-03 14:54:00.705043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56b21e4e1038'
down_revision = 'e009a4fff809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_prompt',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('content', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content')
    )
    op.create_table('post_review',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('post_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('reviewer_comments', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_status',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_post',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('prompt_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['post_prompt.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['post_status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['registered_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_post')
    op.drop_table('post_status')
    op.drop_table('post_review')
    op.drop_table('post_prompt')
    # ### end Alembic commands ###
