"""empty message

Revision ID: e009a4fff809
Revises: 54b78a1267d6
Create Date: 2019-08-24 17:28:12.370132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e009a4fff809'
down_revision = '54b78a1267d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'registered_user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registered_user', type_='unique')
    # ### end Alembic commands ###
